source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DECResizeFontToFitRect_Example', :exclusive => true do
  pod 'DECResizeFontToFitRect', :path => '../'
end

target 'DECResizeFontToFitRect_Tests', :exclusive => true do
  pod 'DECResizeFontToFitRect', :path => '../'

  
end
