source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'DECResizeFontToFitRect_Example' do
  pod 'DECResizeFontToFitRect', :path => '../'
end

target 'DECResizeFontToFitRect_Tests' do
  pod 'DECResizeFontToFitRect', :path => '../'
end
